Adapted for OpenRIA 5.0 rc1
OpenRIAServices/OpenRiaServices.FluentMetadata pull request #8
Opened 2020-11-13 15:20 UTC by papaneko

Remove dependencies to Silverlight and net472, now only targets netstandard 2.0

Update to use on OpenRIA 5.0-rc001

Namespace changes fixes

2020-11-16 10:03 UTC, Daniel-Svensson requested changes
- [x] Ensure all tests passes
- [ ] Ensure sample project works
- [ ] Wait for net5.0-rc1 release to nuget

2020-11-16 10:03 UTC, Daniel-Svensson commented on FluentMetadata.Tests/FluentMetadata.Tests.Web/Web.config
> -      <add name="DomainServiceModule" type="OpenRiaServices.DomainServices.Hosting.DomainServiceHttpModule, OpenRiaServices.DomainServices.Hosting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=2e
I belive namespaces and names needs to be updated to include "Wcf"

2020-11-16 10:03 UTC, Daniel-Svensson commented on FluentMetadata.Tests/FluentMetadata.Tests.Web/Web.config
>      <compilation debug="true" targetFramework="4.6.1"/>
update targetframework to 4.7.2

2020-11-16 10:03 UTC, Daniel-Svensson commented on FluentMetadata/OpenRiaServices.Server.FluentMetadata.csproj
> +    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
should we update to 5.0 ?

2020-11-16 10:45 UTC, papaneko commented on FluentMetadata/OpenRiaServices.Server.FluentMetadata.csproj
> +    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
i first thought of that but saw that OpenRiaServices.Client uses 4.7, so i assumed this was the preferred version for now

or should we update both?

2020-11-16 13:30 UTC, Daniel-Svensson approved these changes

2020-11-16 15:02 UTC, Daniel-Svensson commented
/azp run

2020-11-17 10:52 UTC, Daniel-Svensson commented
/azp run

2020-11-17 13:45 UTC, papaneko commented
/azp run

2020-11-17 15:49 UTC, closed without merging